fix(ci): Remove --gen2 flag for 1st gen functions
ERROR: Function already exists in 1st gen, can't change the environment
FIX: Removed --gen2 flag since functions are 1st generation

Functions were deployed as 1st gen, so we need to use 1st gen
gcloud commands to update environment variables.

This should now successfully update env vars for both functions.